# Generated by Django 5.2.6 on 2025-12-26 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('principal', 'Card Principal (con avatar)'), ('secundaria', 'Card Secundaria')], default='secundaria', help_text='La card principal siempre se muestra primero con el avatar', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Contenido principal de la card')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = primero)')),
                ('vigencia', models.BooleanField(default=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono Font Awesome (ej: fa-solid fa-briefcase)', max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Solo para card principal', null=True, upload_to='about/')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección Acerca de Mí',
                'verbose_name_plural': 'Secciones Acerca de Mí',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AboutListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(limit_choices_to={'tipo': 'secundaria'}, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='index.aboutsection')),
            ],
            options={
                'verbose_name': 'Item de Lista',
                'verbose_name_plural': 'Items de Lista',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AboutBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la tecnología', max_length=50)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono Font Awesome o URL de imagen', max_length=100, null=True)),
                ('icono_tipo', models.CharField(choices=[('fontawesome', 'Font Awesome'), ('url', 'URL de imagen')], default='fontawesome', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(limit_choices_to={'tipo': 'principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='index.aboutsection')),
            ],
            options={
                'verbose_name': 'Badge de Tecnología',
                'verbose_name_plural': 'Badges de Tecnologías',
                'ordering': ['orden'],
            },
        ),
    ]
