# Generated by Django 5.2.6 on 2025-12-24 16:22

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if not blog.slug:
            base_slug = slugify(blog.titulo)
            slug = base_slug
            counter = 1
            # Verificar si el slug ya existe y agregar un número si es necesario
            while Blog.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            blog.slug = slug
            blog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_vigente_blog_vigencia'),
    ]

    operations = [
        # Paso 1: Agregar el campo slug sin restricción unique
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=False),
        ),
        # Paso 2: Generar slugs para registros existentes
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Paso 3: Ahora sí aplicar la restricción unique
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
