# Generated by Django 5.2.6 on 2025-12-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_epigrafe',
            field=models.CharField(blank=True, help_text='Descripción o epígrafe de la imagen destacada', max_length=300, null=True),
        ),
    ]
