# Generated by Django 5.2.6 on 2025-09-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='novedades/')),
                ('link', models.URLField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
