# Generated by Django 5.2.6 on 2025-09-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedad',
            old_name='vigente',
            new_name='vigencia',
        ),
    ]
