# Generated by Django 5.2.6 on 2025-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_rename_vigente_novedad_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal del carousel', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción o subtítulo')),
                ('imagen', models.ImageField(help_text='Imagen de fondo del carousel', upload_to='carousel/')),
                ('nombre_boton', models.CharField(blank=True, help_text='Texto del botón (opcional)', max_length=100, null=True)),
                ('link_boton', models.URLField(blank=True, help_text='URL del botón (opcional)', null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número = primero)')),
                ('vigencia', models.BooleanField(default=True, help_text='Si está activo o no')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(blank=True, help_text='Categorías relacionadas (opcional)', to='configuraciones.categoria')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
