# Generated by Django 5.2.6 on 2025-12-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novedad',
        ),
    ]
