# Generated by Django 5.2.6 on 2025-12-25 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_delete_novedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Biografía corta del autor', null=True)),
                ('website', models.URLField(blank=True, help_text='Sitio web personal', null=True)),
                ('github', models.CharField(blank=True, help_text='Usuario de GitHub', max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='Usuario de LinkedIn', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Usuario de Twitter/X', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
